import { Victim, DroneTelemetry, FlowchartNode, RadioMessage, EquipmentPlugin, ConnectivityPlugin } from '../types';

export const INITIAL_VICTIMS: Victim[] = [
  {
    id: 1,
    codeName: 'SURVIVOR-ALPHA (ID#01)',
    x: 32,
    y: 38,
    sector: 'Sector Alpha - Collapsed Parking Garage',
    trappedMinutes: 84,
    depthFeet: 18.2, // Demonstrating the 20ft deep seismic detection!
    // Drone 1: Sound detection under debris
    acousticDb: 58,
    acousticHz: 840,
    acousticPattern: 'Rhythmic Tapping',
    acousticConfidence: 96,
    // Drone 2: Temperature detection
    temperature: 34.6,
    ambientTemp: 13.5,
    thermalGradientDelta: 21.1,
    thermalConfidence: 89,
    // Drone 3: Vibration detection under 20ft distance
    vibrationHz: 1.8,
    vibrationAmplitude: 0.85,
    vibrationPattern: 'Periodic Kinetic Knock',
    seismicConfidence: 94,
    // Fused Triage Priority
    priorityScore: 96,
    priorityTier: 'P1_CRITICAL',
    estimatedSurvivingHours: 2.8,
    extricationStatus: 'Trapped',
    assignedTeam: 'USAR Team Alpha',
    debrisType: 'Reinforced Concrete Slab',
    safeBreachVector: 'Diagonal trench bore at 45° angle to bypass load-bearing shear wall',
  },
  {
    id: 2,
    codeName: 'SURVIVOR-BRAVO (ID#02)',
    x: 68,
    y: 28,
    sector: 'Sector Bravo - Collapsed Residential Tower',
    trappedMinutes: 140,
    depthFeet: 7.5,
    // Drone 1: Sound detection under debris
    acousticDb: 34,
    acousticHz: 420,
    acousticPattern: 'Weak Breathing',
    acousticConfidence: 82,
    // Drone 2: Temperature detection
    temperature: 32.1, // Hypothermia risk!
    ambientTemp: 12.0,
    thermalGradientDelta: 20.1,
    thermalConfidence: 95,
    // Drone 3: Vibration detection under 20ft distance
    vibrationHz: 1.1,
    vibrationAmplitude: 0.18,
    vibrationPattern: 'Micro-tremor Heartbeat',
    seismicConfidence: 86,
    // Fused Triage Priority
    priorityScore: 92,
    priorityTier: 'P1_CRITICAL',
    estimatedSurvivingHours: 3.4,
    extricationStatus: 'Access Route Cleared',
    assignedTeam: 'USAR Team Beta',
    debrisType: 'Collapsed Brick Masonry',
    safeBreachVector: 'Clear upper drywall barrier; apply pneumatic bag lift to ceiling slab',
  },
  {
    id: 3,
    codeName: 'SURVIVOR-CHARLIE (ID#03)',
    x: 48,
    y: 72,
    sector: 'Sector Charlie - Commercial Plaza Core',
    trappedMinutes: 45,
    depthFeet: 4.8,
    // Drone 1: Sound detection under debris
    acousticDb: 64,
    acousticHz: 1250,
    acousticPattern: 'Distress Cries',
    acousticConfidence: 98,
    // Drone 2: Temperature detection
    temperature: 36.8, // Normal stable vitals
    ambientTemp: 14.2,
    thermalGradientDelta: 22.6,
    thermalConfidence: 93,
    // Drone 3: Vibration detection under 20ft distance
    vibrationHz: 2.6,
    vibrationAmplitude: 0.95,
    vibrationPattern: 'Periodic Kinetic Knock',
    seismicConfidence: 91,
    // Fused Triage Priority
    priorityScore: 78,
    priorityTier: 'P2_HIGH',
    estimatedSurvivingHours: 8.5,
    extricationStatus: 'Breaching Void',
    assignedTeam: null,
    debrisType: 'Twisted Steel & Drywall',
    safeBreachVector: 'Hydraulic cutting of I-beam flank with secondary shoring',
  },
  {
    id: 4,
    codeName: 'SURVIVOR-DELTA (ID#04)',
    x: 82,
    y: 65,
    sector: 'Sector Delta - Subterranean Transit Tunnel',
    trappedMinutes: 190,
    depthFeet: 19.4, // Near 20ft limit!
    // Drone 1: Sound detection under debris
    acousticDb: 28,
    acousticHz: 750,
    acousticPattern: 'Morse Code (SOS)',
    acousticConfidence: 88,
    // Drone 2: Temperature detection
    temperature: 33.4,
    ambientTemp: 11.2,
    thermalGradientDelta: 22.2,
    thermalConfidence: 81,
    // Drone 3: Vibration detection under 20ft distance
    vibrationHz: 1.5,
    vibrationAmplitude: 0.42,
    vibrationPattern: 'Periodic Kinetic Knock',
    seismicConfidence: 95,
    // Fused Triage Priority
    priorityScore: 89,
    priorityTier: 'P1_CRITICAL',
    estimatedSurvivingHours: 4.1,
    extricationStatus: 'Trapped',
    assignedTeam: null,
    debrisType: 'Reinforced Concrete Slab',
    safeBreachVector: 'Vertical core drill pilot hole followed by fiberoptic camera insertion',
  },
  {
    id: 5,
    codeName: 'SURVIVOR-ECHO (ID#05)',
    x: 18,
    y: 78,
    sector: 'Sector Alpha - Perimeter Shanty',
    trappedMinutes: 30,
    depthFeet: 2.1,
    // Drone 1: Sound detection under debris
    acousticDb: 52,
    acousticHz: 920,
    acousticPattern: 'Rhythmic Tapping',
    acousticConfidence: 91,
    // Drone 2: Temperature detection
    temperature: 36.5,
    ambientTemp: 14.5,
    thermalGradientDelta: 22.0,
    thermalConfidence: 94,
    // Drone 3: Vibration detection under 20ft distance
    vibrationHz: 2.2,
    vibrationAmplitude: 0.65,
    vibrationPattern: 'Periodic Kinetic Knock',
    seismicConfidence: 90,
    // Fused Triage Priority
    priorityScore: 64,
    priorityTier: 'P3_MODERATE',
    estimatedSurvivingHours: 14.0,
    extricationStatus: 'Trapped',
    assignedTeam: null,
    debrisType: 'Void Pocket rubble',
    safeBreachVector: 'Manual light debris debris removal with hand saws',
  },
];

export const INITIAL_DRONES: DroneTelemetry[] = [
  {
    id: 'drone_1',
    name: 'Drone 01 - ECHO-RAY',
    callsign: 'ECHO-1',
    type: 'ACOUSTIC',
    sensorLabel: 'Debris Acoustic Beamformer & Microphone Array',
    x: 35,
    y: 40,
    altitudeMeters: 4.2,
    batteryPercent: 88,
    headingDeg: 135,
    status: 'LOCKED_TARGET',
    targetVictimId: 1,
    sensorReadout: 'Acoustic Tapping: 58dB @ 840Hz (96% Confidence)',
    signalStrengthDbm: -54,
    latencyMs: 9.4,
    color: '#38bdf8', // Sky cyan
  },
  {
    id: 'drone_2',
    name: 'Drone 02 - THERMO-HAWK',
    callsign: 'THERMO-2',
    type: 'THERMAL',
    sensorLabel: 'Radiometric FLIR High-Definition Thermal Imager',
    x: 65,
    y: 30,
    altitudeMeters: 6.8,
    batteryPercent: 82,
    headingDeg: 220,
    status: 'LOCKED_TARGET',
    targetVictimId: 2,
    sensorReadout: 'Thermal Isotherm: 32.1°C vs Ambient 12.0°C (Hypothermia Warning)',
    signalStrengthDbm: -58,
    latencyMs: 11.2,
    color: '#f97316', // Orange
  },
  {
    id: 'drone_3',
    name: 'Drone 03 - SEISMO-PROBE',
    callsign: 'SEISMO-3',
    type: 'SEISMIC',
    sensorLabel: 'Subsurface 20ft Micro-Vibration & Geophone Radar',
    x: 78,
    y: 62,
    altitudeMeters: 2.4, // close hover for ground coupling
    batteryPercent: 79,
    headingDeg: 310,
    status: 'SWEEPING',
    targetVictimId: 4,
    sensorReadout: 'Seismic Penetration: 19.4ft depth, 1.5Hz kinetic pulses detected',
    signalStrengthDbm: -61,
    latencyMs: 14.8,
    color: '#a855f7', // Purple
  },
];

export const FLOWCHART_NODES: FlowchartNode[] = [
  {
    id: 'fc-1',
    title: 'Autonomous Swarm Grid Dispatch',
    subtitle: 'Cooperative SLAM & Sector Partitioning',
    role: 'Dispatches all 3 specialized drones across collapsed rubble grid',
    throughput: '3 UAVs active',
    latency: '8 ms',
    status: 'ACTIVE',
  },
  {
    id: 'fc-2',
    title: 'Multi-Modal Debris Sensing',
    subtitle: 'Acoustic + Thermal + 20ft Seismic Detection',
    role: 'Drone 1 listens through rubble, Drone 2 scans heat signatures, Drone 3 penetrates 20ft depth',
    droneResponsible: 'ECHO-1 / THERMO-2 / SEISMO-3',
    throughput: '48.2 kS/s',
    latency: '12 ms',
    status: 'ACTIVE',
    highlight: true,
  },
  {
    id: 'fc-3',
    title: 'Edge Sensor Signal Fusion',
    subtitle: 'Noise Rejection & Coherence Matching',
    role: 'Filters heavy machinery noise; isolates Morse/rhythmic taps and biological thermal curves',
    throughput: '120 frames/s',
    latency: '4 ms',
    status: 'ACTIVE',
  },
  {
    id: 'fc-4',
    title: 'AI Priority & Survivability Triage',
    subtitle: 'Time-to-Rescue Minimization Algorithm',
    role: 'Sorts victims by trapped depth, hypothermia urgency, and audible knocking regularity',
    throughput: '5 targets scored',
    latency: '15 ms',
    status: 'ACTIVE',
    highlight: true,
  },
  {
    id: 'fc-5',
    title: 'USAR Extrication Team Routing',
    subtitle: 'Safe Void Breaching & Tool Allocation',
    role: 'Assigns heavy hydraulic spreaders, pneumatic air bags, and fiberoptic cams to P1 survivors',
    throughput: '2 Teams en route',
    latency: '22 ms',
    status: 'PROCESSING',
  },
  {
    id: 'fc-6',
    title: 'Target Extraction & Field Medical Care',
    subtitle: 'Patient Stabilization & Telemetry Handoff',
    role: 'Verifies live pulse handoff to field medical tents and hospital trauma units',
    throughput: '1 Extricated',
    latency: '30 ms',
    status: 'STANDBY',
  },
];

export const INITIAL_RADIO_MESSAGES: RadioMessage[] = [
  {
    id: 'msg-1',
    sender: 'AEGIS_AI',
    senderLabel: 'AI Swarm Core',
    text: 'SWARM ONLINE: Drone-01 (Acoustic), Drone-02 (Thermal), Drone-03 (Seismic 20ft) connected via mesh.',
    timestamp: '12:08:14',
    priority: 'TACTICAL',
  },
  {
    id: 'msg-2',
    sender: 'DRONE_1',
    senderLabel: 'Drone-01 (ECHO-RAY)',
    text: 'ACOUSTIC LOCK: Detected 3-tap rhythmic knock under Sector Alpha slab. Amplitude 58dB at 840Hz.',
    timestamp: '12:09:02',
    priority: 'CRITICAL',
  },
  {
    id: 'msg-3',
    sender: 'DRONE_3',
    senderLabel: 'Drone-03 (SEISMO-PROBE)',
    text: 'SUBSURFACE RADAR CONFIRMED: Target depth verified at 18.2 FEET below reinforced rubble.',
    timestamp: '12:09:18',
    priority: 'CRITICAL',
  },
  {
    id: 'msg-4',
    sender: 'DRONE_2',
    senderLabel: 'Drone-02 (THERMO-HAWK)',
    text: 'THERMAL FLIR ALERT: Sector Bravo target exhibits hypothermic drop (32.1°C). Life window decreasing.',
    timestamp: '12:09:44',
    priority: 'CRITICAL',
  },
  {
    id: 'msg-5',
    sender: 'USAR_TEAM_ALPHA',
    senderLabel: 'USAR Ground Team Alpha',
    text: 'En route to Sector Alpha with 20T pneumatic lifting bags. Requesting safe breaching vector.',
    timestamp: '12:10:05',
    priority: 'TACTICAL',
  },
];

export const INITIAL_EQUIPMENT_PLUGINS: EquipmentPlugin[] = [
  {
    id: 'eq-1',
    name: 'Pneumatic 20T High-Pressure Air Bags',
    category: 'STABILIZATION',
    status: 'DEPLOYED',
    assignedToSector: 'Sector Alpha',
    description: 'Lifts up to 20 metric tons of concrete rubble slabs to create survivable void openings.',
    weightKg: 18,
    deploymentTimeMinutes: 3,
  },
  {
    id: 'eq-2',
    name: 'Heavy Hydraulic Spreader & Ram (500kN)',
    category: 'BREACHING',
    status: 'DEPLOYED',
    assignedToSector: 'Sector Bravo',
    description: 'Spreads structural steel I-beams and splits collapsed masonry without collapsing voids.',
    weightKg: 24,
    deploymentTimeMinutes: 4,
  },
  {
    id: 'eq-3',
    name: '20-Foot Subsurface Fiberoptic Snake Camera',
    category: 'DETECTION',
    status: 'AVAILABLE',
    description: 'High-definition 360° articulable camera probe for penetrating deep rubble voids.',
    weightKg: 6,
    deploymentTimeMinutes: 2,
  },
  {
    id: 'eq-4',
    name: 'Tactical Hypothermia Rewarming Wrap & Heat Pack',
    category: 'MEDICAL',
    status: 'AVAILABLE',
    description: 'Active convection rewarming blanket for low body temp victims (<34°C).',
    weightKg: 4,
    deploymentTimeMinutes: 1,
  },
  {
    id: 'eq-5',
    name: 'Acoustic Seismic Listening Geophone Ground Stakes',
    category: 'DETECTION',
    status: 'AVAILABLE',
    description: 'Direct ground-coupling geophones to cross-validate Drone 3 subsurface vibration reads.',
    weightKg: 8,
    deploymentTimeMinutes: 5,
  },
];

export const INITIAL_CONNECTIVITY_PLUGINS: ConnectivityPlugin[] = [
  {
    id: 'conn-1',
    name: 'Tactical LoRaWAN Swarm Mesh (915 MHz)',
    protocol: 'LoRa Spread Spectrum (P2P)',
    latency: 14,
    bandwidthKbps: 64,
    active: true,
    status: 'ONLINE',
  },
  {
    id: 'conn-2',
    name: 'Mil-Spec Starlink Tactical Uplink',
    protocol: 'LEO Ku-Band Satellite',
    latency: 28,
    bandwidthKbps: 15000,
    active: true,
    status: 'ONLINE',
  },
  {
    id: 'conn-3',
    name: 'Ad-Hoc 802.11ah HaLow Drone Relay',
    protocol: 'Sub-1GHz Wi-Fi Relay',
    latency: 9,
    bandwidthKbps: 4200,
    active: true,
    status: 'ONLINE',
  },
];
